version: '3'
services:
    wordpress:
        image: visiblevc/wordpress
        # required for mounting bindfs
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        # required on certain cloud hosts
        security_opt:
            - apparmor:unconfined
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./wordpress:/app
            - ./sql:/data
            - ./scripts:/docker-entrypoint-initwp.d
        environment:
            DB_NAME: wordpress
            DB_PASS: root
    db:
        image: mysql:5.7
        volumes:
            - ./wordpress/wp-database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 22222:80
